services:
  db:
    image: postgres:16-alpine
    container_name: pg-user
    environment:
      POSTGRES_DB: user_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d user_service" ]
      interval: 5s
      timeout: 3s
      retries: 10

  user-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: user-service:dev
    container_name: user-service
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SERVER_PORT: "8082"

      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/user_service"
      SPRING_DATASOURCE_USERNAME: "postgres"
      SPRING_DATASOURCE_PASSWORD: "postgres"

      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"

      EVENTS_BASE_URL: "http://host.docker.internal:8083"
      NOTIFICATIONS_BASE_URL: "http://host.docker.internal:8085"
    ports:
      - "8082:8082"

volumes:
  pgdata:
